runtime:
  cache_dir: ./.cache/antora
site:
  title: Okta API security
content:
  sources:
    - url: '.'
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/Mogztter/okta-book-ui/releases/download/v0.0.1/ui-bundle.zip
    snapshot: true
output:
  dir: ./public
